#!/bin/bash
CASPER_VERSION=1_0_0
CASPER_NETWORK=casper-test
cd ~
sudo cp $HOME/casper-node/target/wasm32-unknown-unknown/release/add_bid.wasm /opt
sudo chown casper.casper /opt/add_bid.wasm

sudo -u casper /etc/casper/pull_casper_node_version.sh $CASPER_NETWORK.conf $CASPER_VERSION
sudo -u casper /etc/casper/config_from_example.sh $CASPER_VERSION

KNOWN_ADDRESSES=$(sudo -u casper cat /etc/casper/$CASPER_VERSION/config.toml | grep known_addresses)
KNOWN_VALIDATOR_IPS=$(grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' <<< "$KNOWN_ADDRESSES")
IFS=' ' read -r KNOWN_VALIDATOR_IP _REST <<< "$KNOWN_VALIDATOR_IPS"

echo $KNOWN_VALIDATOR_IP

TRUSTED_HASH=$(curl -s $KNOWN_VALIDATOR_IP:8888/status | jq -r .last_added_block_info.hash | tr -d '\n')
if [ "$TRUSTED_HASH" != "null" ]; then sudo -u casper sed -i "/trusted_hash =/c\trusted_hash = '$TRUSTED_HASH'" /etc/casper/$CASPER_VERSION/config.toml; fi

sudo -u casper /etc/casper/pull_casper_node_version.sh casper-test.conf 1_1_0
sleep 1
sudo -u casper /etc/casper/config_from_example.sh 1_1_0
sleep 1
sudo -u casper /etc/casper/pull_casper_node_version.sh casper-test.conf 1_1_2
sleep 1
sudo -u casper /etc/casper/config_from_example.sh 1_1_2
sleep 1
sudo -u casper /etc/casper/pull_casper_node_version.sh casper-test.conf 1_2_0
sleep 1
sudo -u casper /etc/casper/config_from_example.sh 1_2_0
sleep 1
sudo -u casper /etc/casper/pull_casper_node_version.sh casper-test.conf 1_2_1
sleep 1
sudo -u casper /etc/casper/config_from_example.sh 1_2_1
sleep 1
sudo -u casper /etc/casper/pull_casper_node_version.sh casper-test.conf 1_3_1
sleep 1
sudo -u casper /etc/casper/config_from_example.sh 1_3_1
sleep 1
sudo -u casper /etc/casper/pull_casper_node_version.sh casper-test.conf 1_3_2
sleep 1
sudo -u casper /etc/casper/config_from_example.sh 1_3_2
sleep 1
sudo -u casper /etc/casper/pull_casper_node_version.sh casper-test.conf 1_3_4
sleep 1
sudo -u casper /etc/casper/config_from_example.sh 1_3_4
sleep 1
sudo -u casper /etc/casper/pull_casper_node_version.sh casper-test.conf 1_4_1
sleep 1
sudo -u casper /etc/casper/config_from_example.sh 1_4_1
sleep 1
sudo -u casper /etc/casper/pull_casper_node_version.sh casper-test.conf 1_4_2
sleep 1
sudo -u casper /etc/casper/config_from_example.sh 1_4_2
sleep 1
sudo -u casper /etc/casper/pull_casper_node_version.sh casper-test.conf 1_4_3
sleep 1
sudo -u casper /etc/casper/config_from_example.sh 1_4_3
sleep 1
sudo -u casper /etc/casper/pull_casper_node_version.sh casper-test.conf 1_4_4
sleep 1
sudo -u casper /etc/casper/config_from_example.sh 1_4_4
sleep 1
sudo -u casper /etc/casper/pull_casper_node_version.sh casper-test.conf 1_4_5
sleep 1
sudo -u casper /etc/casper/config_from_example.sh 1_4_5
sleep 1
sudo -u casper /etc/casper/pull_casper_node_version.sh casper-test.conf 1_4_6
sleep 1
sudo -u casper /etc/casper/config_from_example.sh 1_4_6
sleep 1
sudo -u casper /etc/casper/pull_casper_node_version.sh casper-test.conf 1_4_7
sleep 1
sudo -u casper /etc/casper/config_from_example.sh 1_4_7
sleep 1
sudo -u casper /etc/casper/pull_casper_node_version.sh casper-test.conf 1_4_8
sleep 1
sudo -u casper /etc/casper/config_from_example.sh 1_4_8
sleep 1
sudo -u casper /etc/casper/pull_casper_node_version.sh casper-test.conf 1_4_10
sleep 1
sudo -u casper /etc/casper/config_from_example.sh 1_4_10
sleep 1
sudo -u casper /etc/casper/pull_casper_node_version.sh casper-test.conf 1_4_13
sleep 1
sudo -u casper /etc/casper/config_from_example.sh 1_4_13
sleep 1
sudo -u casper /etc/casper/pull_casper_node_version.sh casper-test.conf 1_4_15
sleep 1
sudo -u casper /etc/casper/config_from_example.sh 1_4_15


sudo logrotate -f /etc/logrotate.d/casper-node
sudo systemctl start casper-node-launcher; sleep 2
systemctl status casper-node-launcher

echo "##########################################"
echo "Installation finished"
echo "Bond to the network"
echo "##########################################"
sudo apt update && sudo apt upgrade -y

PUBLIC_KEY_HEX=$(sudo -u casper cat /etc/casper/validator_keys/public_key_hex)
STATE_ROOT_HASH=$(casper-client get-state-root-hash --node-address http://127.0.0.1:7777 | jq -r '.result | .state_root_hash')
PURSE_UREF=$(sudo -u casper casper-client query-state --node-address http://127.0.0.1:7777 --key "$PUBLIC_KEY_HEX" --state-root-hash "$STATE_ROOT_HASH" | jq -r '.result | .stored_value | .Account | .main_purse')
casper-client get-balance --node-address http://127.0.0.1:7777 --purse-uref "$PURSE_UREF" --state-root-hash "$STATE_ROOT_HASH" | jq -r '.result | .balance_value'

PUBLIC_KEY_HEX=$(sudo -u casper cat /etc/casper/validator_keys/public_key_hex)
CHAIN_NAME=$(curl -s http://127.0.0.1:8888/status | jq -r '.chainspec_name')

sudo -u casper casper-client put-deploy \
    --chain-name "$CHAIN_NAME" \
    --node-address "http://127.0.0.1:7777/" \
    --secret-key "/etc/casper/validator_keys/secret_key.pem" \
    --session-path "/opt/add_bid.wasm" \
    --payment-amount 75000000000 \
    --gas-price=1 \
    --session-arg=public_key:"public_key='$PUBLIC_KEY_HEX'" \
    --session-arg=amount:"u512='900000000000'" \
    --session-arg=delegation_rate:"u8='10'"
